#! /bin/sh
bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         3
bspc config window_gap           10

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color \#282828
bspc config focused_border_color \#fb4934

bspc rule -a Chromium desktop='^2'
